### ISSUE TITLE
Description icon not visible

### ISSUE THREAD

**Issue by SudoSu-bham** [sugarlabs/block-party-activity#36]
![Capture](https://github.com/sugarlabs/block-party-activity/assets/55135022/6ee8185b-239e-418a-a9b8-8a5f8007c04a)

The description icon is not visible when activity is run in sugar environment.

**Comment by quozl** [comment]
Duplicate of https://github.com/sugarlabs/sugar-toolkit-gtk3/issues/465 and affects all GTK 3 activities.  Closing this issue.  Please work the issue in the relevant repository, thanks.
